<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Correlation id for a single update command. Generated by the API when a
     * command is created (request-update or heartbeat dispatch) and echoed back
     * by the connector on every ack. Lets both sides deduplicate a command
     * (so it is never executed twice) and match acks to the command in flight.
     */
    public function up(): void
    {
        Schema::table('sites', function (Blueprint $table) {
            $table->string('update_command_id', 64)
                ->nullable()
                ->after('update_command_type');
        });
    }

    public function down(): void
    {
        Schema::table('sites', function (Blueprint $table) {
            $table->dropColumn('update_command_id');
        });
    }
};
